# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='item',
            name='excludes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='public',
        ),
    ]
