# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-11 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20180211_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contents',
            field=models.TextField(blank=True, help_text='Separate each item by comma', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='excludes',
            field=models.TextField(blank=True, help_text='Separate each item by comma', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
